name: "Shoichi Imamura"
bio: "I'm a software engineer."
job: "Software Engineer"
location: "Japan"
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatarEmail: "immrshich@gmail.com"
# Your profile picture
# Overwritten by your gravatar image if `author.gravatarEmail` is filled
# picture: "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
# Your Twitter username without the @. E.g : thibaudlepretre
# twitter: "thibaudlepretre"
# Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
# googlePlus: "+ThibaudLepretre"

